@startuml
!pragma teoz true

protocol SensorService {
    ** Sensor **
    |_ Zero Offset <- void
    |_ ADC Raw -> Uint32
    |_ Power -> Uint16
    |_ Accel Raw -> float[3]
    |_ Gyro Raw -> float[3]
    |_ Orientation -> float[4]
    |_ Cadence -> Uint16
}

protocol CalibrationService {
    ** Calibration **
    |_ GetCalibration -> cal_data_t
    |_ SetCalibration <- cal_data_t
}

protocol CoreService {
    ** Core **
    |_ GetState -> state_t
    |_ CoreRequest <- core_request_t
}

SensorService -[hidden] CalibrationService
CalibrationService -[hidden] CoreService

@enduml
